### ISSUE TITLE
Minimum / Maximum values are incorrect

### ISSUE THREAD

**Issue by epotter2297** [ecyrbe/zodios-openapi#36]
If I have an API definition with a parameter like this:
```js
{
  name: 'limit',
  type: 'Query',
  schema: z.number().positive().default(10),
},
```
The generated OpenAPI doc shows `"minimum":0` for `limit`. This should be `1`, since `0` is invalid input for `.positive()`. The same issue applies to `.negative()`, where `maximum` should be `-1` instead of `0`

**Comment by ecyrbe** [comment]
Actually, I think the output is good since it produces also an exclusive minimum :  
```json
          {
            "description": "Limit the number of users",
            "in": "query",
            "name": "limit",
            "required": false,
            "schema": {
              "default": 10,
              "exclusiveMinimum": true,
              "minimum": 0,
              "type": "number",
            },
          },
```

**Comment by epotter2297** [comment]
Ah yep, you're right. I think the issue is just with `swagger-ui-express` not preventing you from sending 0 in that case.
