### ISSUE TITLE
Support Recursive Types

### ISSUE THREAD

**Issue by epotter2297** [ecyrbe/zodios-openapi#60]
Right now zodios-openapi does not support recursive types. Using the recursive example from the [zod README](https://github.com/colinhacks/zod#recursive-types)
```ts
interface Category {
  name: string;
  subcategories: Category[];
}

// cast to z.ZodType<Category>
const Category: z.ZodType<Category> = z.lazy(() =>
  z.object({
    name: z.string(),
    subcategories: z.array(Category),
  })
);
```
the openapi that is generated from this is:
```json
"subcategories": {"type":"array","items":{}},
```

**Comment by ecyrbe** [comment]
Hello, it's technically not possible. Lazy types are not introspectable, since lazy is a function.

**Comment by epotter2297** [comment]
It should be possible though since it has an interface being manually assigned. This example actually works recursively if I try to access it via `req.body.category.subcategories[0].subcategories[0]`, for example.
It would just only be aware of what you put in the interface and not anything extra in the zod definition, doing that would obviously be impossible.

**Comment by epotter2297** [comment]
Hmm, after briefly looking into the code for zodios-openapi, even if it's not impossible it would definitely be a big undertaking 🤔
I do have some recursive schemas I would like to show up correctly in OpenAPI, maybe an optional `jsonSchema` property in `makeApi()` would be a good compromise? For example:
```ts
{
  method: 'post',
  path: '/libraryItem',
  alias: 'createLibraryItem',
  description: 'Creates a library item',
  status: 201,
  parameters: [
    {
      name: 'body',
      type: 'Body',
      schema: RecursiveSchema,
      jsonSchema: manuallyDefinedJsonSchema,
    },
  ],
  response: z.strictObject({ status: z.enum(['Created']) }),
  jsonSchema: itCouldGoHereToo,
},
```
Then I could just use `zod-to-json-schema` myself and make it recursive, or do whatever else I want.

**Comment by epotter2297** [comment]
@ecyrbe Quick update, I just saw that `zod-to-json-schema` has an [open issue](https://github.com/StefanTerdell/zod-to-json-schema/issues/29) for this exact problem, so it looks like they will fix it on their end.

**Comment by ecyrbe** [comment]
If they have a trick to handle this, good news.
Else, by the end of the year, zodios v11 will support any validation library, and will then support native json schema if you need to handle recursive schemas. This will mean using ajv instead of zod to declare schemas.
