### ISSUE TITLE
Security Scheme extensions

### ISSUE THREAD

**Issue by nadilas** [ecyrbe/zodios-openapi#96]
Hi,

we're trying to integrate Speakeasy with Zodios. According to them, the following extensions need to be set on the security scheme definition [see docs](https://docs.speakeasyapi.dev/docs/integrate-speakeasy/manage-api-keys#update-your-api-configuration):

| Field                | Type
|----------------------|-----------------|
| x-google-issuer      | The issuer of a credential, should be set to "https://app.speakeasyapi.dev/v1/auth/oauth/{your-speakeasy-worksapce-id}" |
| x-google-jwks_uri    | The URI of the public key set to validate the JSON Web Token (JWT) signature. Set this to "https://app.speakeasyapi.dev/v1/auth/oauth/{your-speakeasy-workspace-id}/.well-known/jwks.json".           |
| x-google-audiences   | Your Speakeasy workspace idenfitifer.

Can't seem to add the extensions when using the `openApiBuilder` with `oauth2Scheme`:
```
Type '{ authorizationUrl: string; "x-google-issuer": string; "x-google-jwks_uri": string; "x-google-audiences": string; }' is not assignable to type '{ authorizationUrl: string; refreshUrl?: string | undefined; scopes: { [scope: string]: string; }; }'.
  Object literal may only specify known properties, and '"x-google-issuer"' does not exist in type '{ authorizationUrl: string; refreshUrl?: string | undefined; scopes: { [scope: string]: string; }; }'.ts(2322)
```

Can we introduce a generic for the `oauth2Scheme` helper method to enable extensions?

**Comment by ecyrbe** [comment]
Hello,
I have no experience with security extensions. 
But zodios is just a simple wrapper around those. So if you want you can submit a `oauth2ExtensionScheme` to zodios openapi helpers, I'll be glad to merge it on zodios. 
Or you can create your own helper and use it on your own project without publishing it on zodios.
